import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import {
  Code2, Bug, FolderGit2, Layers, MessageSquare, Shield, Zap,
  ArrowRight, ChevronRight, Terminal, Database, FileCode, GitBranch,
  Cpu, Globe, Server, HardDrive, Sparkles, Play, Check
} from 'lucide-react';

const capabilities = [
  {
    icon: Code2,
    title: 'AI Code Generation',
    desc: 'Generate production-ready code from natural language descriptions. Supports React, Vue, Angular, Node.js, Python, Go, and more.',
    features: ['Full-stack code generation', 'TypeScript support', 'Best practices enforcement', 'Custom templates'],
    color: 'purple',
    demo: `// Generated by YawtAI
import express from 'express';
import { Pool } from 'pg';
import cors from 'cors';

const app = express();
app.use(cors());
app.use(express.json());

const pool = new Pool({
  connectionString: process.env.DATABASE_URL
});

app.get('/api/transactions', async (req, res) => {
  const { rows } = await pool.query(
    'SELECT * FROM transactions ORDER BY created_at DESC LIMIT 50'
  );
  res.json({ data: rows });
});`,
  },
  {
    icon: Bug,
    title: 'AI Debugging',
    desc: 'Paste your error stack trace and get instant explanations, root cause analysis, and fixed code.',
    features: ['Stack trace analysis', 'Root cause detection', 'Auto-fix generation', 'Prevention tips'],
    color: 'red',
    demo: `// Bug Analysis by YawtAI
// Error: TypeError: Cannot read property 'map' of undefined

// Root Cause:
// The 'users' state is not initialized as an array

// Fix:
const [users, setUsers] = useState<User[]>([]);

// Before (buggy):
// const [users, setUsers] = useState();

// Prevention: Always initialize state with
// the correct type and default value.`,
  },
  {
    icon: FolderGit2,
    title: 'Codebase Understanding',
    desc: 'Connect your GitHub repo and ask questions about architecture, patterns, and improvements.',
    features: ['Repository scanning', 'Code embeddings', 'RAG-powered Q&A', 'Architecture analysis'],
    color: 'blue',
    demo: `// Repository Analysis by YawtAI
// Repo: github.com/user/ecommerce-app

Q: "Explain the authentication system"

A: The auth system uses JWT tokens with 
   refresh token rotation. Key files:
   
   - src/auth/jwt.service.ts (token generation)
   - src/auth/guards/auth.guard.ts (route protection)
   - src/auth/strategies/local.strategy.ts
   
   Security: bcrypt for password hashing,
   HttpOnly cookies for token storage.`,
  },
  {
    icon: Layers,
    title: 'Project Generator',
    desc: 'Generate complete full-stack projects with frontend, backend, database, Docker, and documentation.',
    features: ['Full-stack scaffolding', 'Docker configuration', 'Database schemas', 'README generation'],
    color: 'green',
    demo: `// Project Generated by YawtAI
// Prompt: "SaaS analytics dashboard"

project-structure/
├── frontend/
│   ├── src/
│   │   ├── components/
│   │   ├── pages/
│   │   └── hooks/
│   └── package.json
├── backend/
│   ├── src/
│   │   ├── routes/
│   │   ├── models/
│   │   └── middleware/
│   └── package.json
├── docker-compose.yml
├── schema.sql
└── README.md`,
  },
  {
    icon: MessageSquare,
    title: 'AI Coding Chat',
    desc: 'Have natural conversations about code. Get explanations, refactoring suggestions, and guidance.',
    features: ['Context-aware responses', 'Code explanations', 'Refactoring help', 'Best practices'],
    color: 'cyan',
    demo: `// Chat with YawtAI
You: "How do I optimize this database query?"

YawtAI: "I see several optimization opportunities:

1. Add an index on the 'created_at' column
2. Use pagination instead of LIMIT/OFFSET
3. Consider a materialized view for the 
   aggregation query
4. Use connection pooling with pg-pool

Here's the optimized version..."`,
  },
  {
    icon: Shield,
    title: 'Security Analysis',
    desc: 'Identify vulnerabilities, security anti-patterns, and get hardening recommendations.',
    features: ['Vulnerability scanning', 'OWASP compliance', 'Dependency audit', 'Security fixes'],
    color: 'amber',
    demo: `// Security Report by YawtAI
// Severity: HIGH

⚠ SQL Injection vulnerability found
  File: src/routes/users.js:42
  
  // Vulnerable:
  db.query(\`SELECT * FROM users 
    WHERE id = \${req.params.id}\`)
  
  // Fixed:
  db.query('SELECT * FROM users WHERE id = $1',
    [req.params.id])
    
  Impact: Unauthorized data access
  Fix: Use parameterized queries`,
  },
];

const architecture = [
  { icon: Globe, label: 'Frontend', desc: 'React / Next.js', color: 'text-cyan-400' },
  { icon: Server, label: 'API Server', desc: 'Node.js / Express', color: 'text-green-400' },
  { icon: Cpu, label: 'AI Engine', desc: 'RAG + LLM', color: 'text-purple-400' },
  { icon: Database, label: 'PostgreSQL', desc: 'Primary DB', color: 'text-blue-400' },
  { icon: HardDrive, label: 'Qdrant', desc: 'Vector DB', color: 'text-amber-400' },
  { icon: Zap, label: 'Redis', desc: 'Cache Layer', color: 'text-red-400' },
];

const colorMap: Record<string, { bg: string; border: string; text: string; gradient: string }> = {
  purple: { bg: 'bg-purple-500/10', border: 'border-purple-500/20', text: 'text-purple-400', gradient: 'from-purple-600 to-purple-800' },
  red: { bg: 'bg-red-500/10', border: 'border-red-500/20', text: 'text-red-400', gradient: 'from-red-600 to-red-800' },
  blue: { bg: 'bg-blue-500/10', border: 'border-blue-500/20', text: 'text-blue-400', gradient: 'from-blue-600 to-blue-800' },
  green: { bg: 'bg-emerald-500/10', border: 'border-emerald-500/20', text: 'text-emerald-400', gradient: 'from-emerald-600 to-emerald-800' },
  cyan: { bg: 'bg-cyan-500/10', border: 'border-cyan-500/20', text: 'text-cyan-400', gradient: 'from-cyan-600 to-cyan-800' },
  amber: { bg: 'bg-amber-500/10', border: 'border-amber-500/20', text: 'text-amber-400', gradient: 'from-amber-600 to-amber-800' },
};

const ProductsPage: React.FC = () => {
  const [activeCapability, setActiveCapability] = useState(0);

  return (
    <div className="bg-slate-950 text-white pt-24">
      {/* Hero */}
      <section className="py-20 relative">
        <div className="absolute inset-0 bg-gradient-to-b from-purple-900/10 to-transparent" />
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-400 text-xs font-medium mb-6">
            <Sparkles className="w-3.5 h-3.5" />
            YawtAI Product Suite
          </div>
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold mb-6">
            <span className="bg-gradient-to-r from-white to-slate-300 bg-clip-text text-transparent">
              The complete AI toolkit
            </span>
            <br />
            <span className="bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent">
              for modern developers
            </span>
          </h1>
          <p className="text-lg text-slate-400 max-w-2xl mx-auto mb-10">
            From code generation to full project scaffolding, YawtAI provides everything you need to build software faster with AI-powered assistance.
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            <Link
              to="/demo"
              className="px-6 py-3 bg-gradient-to-r from-purple-600 to-blue-600 text-white font-semibold rounded-xl hover:from-purple-500 hover:to-blue-500 transition-all shadow-lg shadow-purple-500/25 flex items-center gap-2"
            >
              <Play className="w-4 h-4" />
              Try Live Demo
            </Link>
            <Link
              to="/docs"
              className="px-6 py-3 border border-slate-700 text-slate-300 font-medium rounded-xl hover:bg-white/5 transition-all flex items-center gap-2"
            >
              View Documentation
            </Link>
          </div>
        </div>
      </section>

      {/* Capabilities Detail */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-bold mb-4 bg-gradient-to-r from-white to-slate-300 bg-clip-text text-transparent">
              Core Capabilities
            </h2>
            <p className="text-slate-400 max-w-xl mx-auto">
              Six powerful AI features designed to cover every aspect of the development lifecycle.
            </p>
          </div>

          {/* Tab Navigation */}
          <div className="flex flex-wrap justify-center gap-2 mb-12">
            {capabilities.map((cap, i) => {
              const colors = colorMap[cap.color];
              return (
                <button
                  key={cap.title}
                  onClick={() => setActiveCapability(i)}
                  className={`flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium transition-all ${
                    activeCapability === i
                      ? `${colors.bg} ${colors.text} border ${colors.border}`
                      : 'text-slate-400 hover:text-white hover:bg-white/5 border border-transparent'
                  }`}
                >
                  <cap.icon className="w-4 h-4" />
                  {cap.title}
                </button>
              );
            })}
          </div>

          {/* Active Capability Detail */}
          {(() => {
            const cap = capabilities[activeCapability];
            const colors = colorMap[cap.color];
            return (
              <div className="grid lg:grid-cols-2 gap-8">
                <div>
                  <div className={`w-14 h-14 rounded-xl ${colors.bg} border ${colors.border} flex items-center justify-center mb-6`}>
                    <cap.icon className={`w-7 h-7 ${colors.text}`} />
                  </div>
                  <h3 className="text-2xl font-bold text-white mb-4">{cap.title}</h3>
                  <p className="text-slate-400 leading-relaxed mb-6">{cap.desc}</p>
                  <ul className="space-y-3 mb-8">
                    {cap.features.map((f) => (
                      <li key={f} className="flex items-center gap-3 text-sm text-slate-300">
                        <div className={`w-5 h-5 rounded-full ${colors.bg} flex items-center justify-center`}>
                          <Check className={`w-3 h-3 ${colors.text}`} />
                        </div>
                        {f}
                      </li>
                    ))}
                  </ul>
                  <Link
                    to="/demo"
                    className={`inline-flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r ${colors.gradient} text-white text-sm font-semibold rounded-lg transition-all hover:opacity-90`}
                  >
                    Try {cap.title} <ArrowRight className="w-4 h-4" />
                  </Link>
                </div>
                <div className="relative">
                  <div className={`absolute -inset-2 bg-gradient-to-r ${colors.gradient} rounded-2xl blur-xl opacity-10`} />
                  <div className="relative bg-slate-900/90 backdrop-blur-xl rounded-2xl border border-slate-700/50 overflow-hidden">
                    <div className="flex items-center gap-2 px-4 py-3 bg-slate-800/50 border-b border-slate-700/50">
                      <div className="flex gap-1.5">
                        <div className="w-3 h-3 rounded-full bg-red-500/80" />
                        <div className="w-3 h-3 rounded-full bg-yellow-500/80" />
                        <div className="w-3 h-3 rounded-full bg-green-500/80" />
                      </div>
                      <span className="text-xs text-slate-500 ml-2 font-mono">{cap.title.toLowerCase().replace(/\s/g, '-')}</span>
                    </div>
                    <pre className="p-6 text-sm font-mono text-slate-300 overflow-x-auto leading-relaxed">
                      <code>{cap.demo}</code>
                    </pre>
                  </div>
                </div>
              </div>
            );
          })()}
        </div>
      </section>

      {/* Architecture */}
      <section className="py-20 bg-slate-900/30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 text-xs font-medium mb-4">
              <Cpu className="w-3.5 h-3.5" />
              Architecture
            </div>
            <h2 className="text-3xl sm:text-4xl font-bold mb-4 bg-gradient-to-r from-white to-slate-300 bg-clip-text text-transparent">
              Enterprise-grade AI architecture
            </h2>
            <p className="text-slate-400 max-w-2xl mx-auto">
              Built on RAG (Retrieval Augmented Generation) with code embeddings and vector search for context-aware AI responses.
            </p>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
            {architecture.map((item) => (
              <div key={item.label} className="bg-slate-900/50 rounded-xl border border-slate-800/50 p-5 text-center hover:border-slate-700 transition-all group">
                <item.icon className={`w-8 h-8 ${item.color} mx-auto mb-3`} />
                <div className="text-sm font-semibold text-white mb-1">{item.label}</div>
                <div className="text-xs text-slate-500">{item.desc}</div>
              </div>
            ))}
          </div>

          {/* API Endpoints */}
          <div className="mt-16">
            <h3 className="text-xl font-bold text-white mb-6 text-center">API Endpoints</h3>
            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
              {[
                { method: 'POST', path: '/ai/chat', desc: 'AI coding chat' },
                { method: 'POST', path: '/ai/debug', desc: 'Error analysis' },
                { method: 'POST', path: '/ai/generate-project', desc: 'Project scaffolding' },
                { method: 'POST', path: '/ai/repo-analysis', desc: 'Repository Q&A' },
              ].map((ep) => (
                <div key={ep.path} className="bg-slate-900/50 rounded-xl border border-slate-800/50 p-4 hover:border-purple-500/30 transition-all">
                  <div className="flex items-center gap-2 mb-2">
                    <span className="px-2 py-0.5 rounded text-xs font-bold bg-green-500/10 text-green-400 border border-green-500/20">
                      {ep.method}
                    </span>
                    <code className="text-sm text-purple-400 font-mono">{ep.path}</code>
                  </div>
                  <p className="text-xs text-slate-500">{ep.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Example Prompt */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold mb-4 bg-gradient-to-r from-white to-slate-300 bg-clip-text text-transparent">
              See it in action
            </h2>
            <p className="text-slate-400">
              Example: "Build a fintech dashboard using React, Node.js and PostgreSQL"
            </p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {[
              { icon: FileCode, title: 'Frontend Code', desc: 'React dashboard with charts, tables, and real-time data visualization', color: 'text-cyan-400' },
              { icon: Server, title: 'Backend API', desc: 'Express.js REST API with authentication, CRUD operations, and middleware', color: 'text-green-400' },
              { icon: Database, title: 'Database Schema', desc: 'PostgreSQL schema with users, transactions, accounts, and audit tables', color: 'text-blue-400' },
              { icon: Layers, title: 'Docker Setup', desc: 'docker-compose.yml with frontend, backend, database, and Redis services', color: 'text-purple-400' },
            ].map((item) => (
              <div key={item.title} className="bg-slate-900/50 rounded-xl border border-slate-800/50 p-6 hover:border-slate-700 transition-all">
                <item.icon className={`w-8 h-8 ${item.color} mb-4`} />
                <h3 className="text-lg font-semibold text-white mb-2">{item.title}</h3>
                <p className="text-sm text-slate-400">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl font-bold mb-4 bg-gradient-to-r from-white to-slate-300 bg-clip-text text-transparent">
            Start building with YawtAI
          </h2>
          <p className="text-slate-400 max-w-xl mx-auto mb-8">
            Free to use during beta. No credit card required.
          </p>
          <Link
            to="/demo"
            className="inline-flex items-center gap-2 px-8 py-4 bg-gradient-to-r from-purple-600 to-blue-600 text-white font-semibold rounded-xl hover:from-purple-500 hover:to-blue-500 transition-all shadow-xl shadow-purple-500/25 text-lg"
          >
            <Play className="w-5 h-5" />
            Launch YawtAI
            <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      </section>
    </div>
  );
};

export default ProductsPage;
